# Generated by Django 3.1.7 on 2021-04-30 18:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_De_Nacimiento', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Motivo', models.CharField(max_length=15)),
                ('Titulo', models.CharField(max_length=30)),
                ('Comuna', models.CharField(max_length=30)),
                ('Region', models.CharField(max_length=30)),
                ('Fecha', models.DateTimeField(default=datetime.datetime(2021, 4, 30, 14, 14, 34, 648428))),
                ('Tipo_Animal', models.CharField(max_length=30)),
                ('Sexo', models.CharField(max_length=15)),
                ('Descripcion', models.CharField(max_length=250)),
                ('Foto', models.ImageField(upload_to='')),
                ('Estado_del_Aviso', models.BooleanField()),
                ('Nombre_De_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Avisos.usuario')),
            ],
        ),
    ]
