# Generated by Django 3.2 on 2021-05-03 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avisos', '0002_auto_20210502_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 22, 27, 56, 370295)),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='Foto',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
