# Generated by Django 3.1.7 on 2021-06-15 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avisos', '0004_auto_20210614_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='Edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 15, 36, 12, 569953)),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 15, 36, 12, 568954)),
        ),
    ]
