# Generated by Django 3.1.1 on 2021-06-19 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avisos', '0005_auto_20210615_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='Comentarios',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 17, 56, 56, 569151)),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='Foto',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='Region',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 19, 17, 56, 56, 568142)),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='Foto',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='Region',
            field=models.CharField(max_length=40),
        ),
    ]
