# Generated by Django 3.2 on 2021-06-21 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avisos', '0010_auto_20210621_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 12, 9, 47, 774096)),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 12, 9, 47, 774096)),
        ),
    ]
