# Generated by Django 3.2 on 2021-06-21 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avisos', '0013_auto_20210621_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='Comentarios',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 13, 9, 19, 4020)),
        ),
        migrations.AlterField(
            model_name='adopcion',
            name='Region',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 13, 9, 19, 4020)),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='Region',
            field=models.CharField(max_length=40),
        ),
    ]
