# Generated by Django 3.2 on 2021-06-21 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avisos', '0014_auto_20210621_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 16, 46, 7, 948205)),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 16, 46, 7, 946205)),
        ),
    ]
