# Generated by Django 3.2 on 2021-06-21 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Avisos', '0015_auto_20210621_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 17, 24, 24, 232405)),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='Fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 21, 17, 24, 24, 230407)),
        ),
    ]
